[features]
seeds = false

[programs.localnet]
timelock_token = "time2Z2SCnn3qYg3ULKVtdkh8YmZ5jFdKicnA1W2YnJ"

[programs.devnet]
timelock_token = "time2Z2SCnn3qYg3ULKVtdkh8YmZ5jFdKicnA1W2YnJ"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "./provider-key.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"