[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
swap_validator = "sWvA66HNNvgamibZe88v3NN5nQwE8tp3KitfViFjukA"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/jeffyanta/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
